//======================================
//======       AutoGenerated       =====
//======================================

namespace Shared.Protocol
{
    public enum CSPacketProtocol: int
    {
        Invalid,

        CS_Ping,
        CS_Login,
        CS_CreateAccount,
        CS_ChatMessage,
    }
}
