//======================================
//======       AutoGenerated       =====
//======================================

using Shared.Network;
using System;

namespace Shared.Protocol
{
    public sealed class CSPacketSender
    {
        private AsyncTcpConnection m_Connection;
        public CSPacketSender(AsyncTcpConnection connection)
        {
            m_Connection = connection ?? throw new ArgumentNullException(nameof(connection));
        }

        public void SEND_CS_Ping(long sequenceNumber)
        {
            var packet = CSPacketPacker.Pack_CS_Ping(sequenceNumber);
            m_Connection.Send(packet);
        }

        public void SEND_CS_Login(string id, string password)
        {
            var packet = CSPacketPacker.Pack_CS_Login(id, password);
            m_Connection.Send(packet);
        }

        public void SEND_CS_CreateAccount(string id, string password)
        {
            var packet = CSPacketPacker.Pack_CS_CreateAccount(id, password);
            m_Connection.Send(packet);
        }

        public void SEND_CS_ChatMessage(string message)
        {
            var packet = CSPacketPacker.Pack_CS_ChatMessage(message);
            m_Connection.Send(packet);
        }

    }
}
