//======================================
//======       AutoGenerated       =====
//======================================
namespace Shared.Protocol
{
    public interface ICSPacketHandler
    {
        void HANDLE_CS_Ping(long sequenceNumber);
        void HANDLE_CS_Login(string id, string password);
        void HANDLE_CS_CreateAccount(string id, string password);
        void HANDLE_CS_ChatMessage(string message);
    }
}
