//======================================
//======       AutoGenerated       =====
//======================================

//======================================
//======       AutoGenerated       =====
//======================================
namespace roject.Chat.Shared.Protocol
{
    public interface ISCPacketHandler
    {
        void HANDLE_SC_Pong(long sequenceNumber);
        void HANDLE_SC_Login(long linkedAccountId);
        void HANDLE_SC_CreateAccount(long linkedAccountId);
        void HANDLE_SC_ChatMessage();
    }
}
