//======================================
//======       AutoGenerated       =====
//======================================

using Shared.Network;
using System;

namespace Shared.Protocol
{
    public sealed class SCPacketSender
    {
        private AsyncTcpConnection m_Connection;
        public SCPacketSender(AsyncTcpConnection connection)
        {
            m_Connection = connection ?? throw new ArgumentNullException(nameof(connection));
        }

        public void SEND_SC_Pong(long sequenceNumber)
        {
            var packet = SCPacketPacker.Pack_SC_Pong(sequenceNumber);
            m_Connection.Send(packet);
        }

        public void SEND_SC_Login(long linkedAccountId)
        {
            var packet = SCPacketPacker.Pack_SC_Login(linkedAccountId);
            m_Connection.Send(packet);
        }

        public void SEND_SC_CreateAccount(long linkedAccountId)
        {
            var packet = SCPacketPacker.Pack_SC_CreateAccount(linkedAccountId);
            m_Connection.Send(packet);
        }

        public void SEND_SC_ChatMessage()
        {
            var packet = SCPacketPacker.Pack_SC_ChatMessage();
            m_Connection.Send(packet);
        }

    }
}
