//======================================
//======       AutoGenerated       =====
//======================================

using Shared.Network;
using Shared.Util;
using System;

namespace Shared.Protocol
{
    public static class SCPacketPacker
    {
        private static void WriteHeader(BinaryEncoder encoder, SCPacketProtocol protocol, int bodySize)
        {
            encoder.Write(in protocol);
            encoder.Write(in bodySize);
        }
        public static ArraySegment<byte> Pack_SC_Pong(long sequenceNumber)
        {
            var protocol = SCPacketProtocol.SC_Pong;

            int bodySize = 0;
            bodySize += sequenceNumber.SizeForWrite();

            int packetSize = SCPacketHeader.HEADER_SIZE + bodySize;

            var packetBuffer = new ArraySegment<byte>(new byte[packetSize]);
            using(var encoder = new BinaryEncoder(packetBuffer))
            {
                WriteHeader(encoder, protocol, bodySize);
                encoder.Write(in sequenceNumber);
            }
            return packetBuffer;
        }
        public static ArraySegment<byte> Pack_SC_Login(long linkedAccountId)
        {
            var protocol = SCPacketProtocol.SC_Login;

            int bodySize = 0;
            bodySize += linkedAccountId.SizeForWrite();

            int packetSize = SCPacketHeader.HEADER_SIZE + bodySize;

            var packetBuffer = new ArraySegment<byte>(new byte[packetSize]);
            using(var encoder = new BinaryEncoder(packetBuffer))
            {
                WriteHeader(encoder, protocol, bodySize);
                encoder.Write(in linkedAccountId);
            }
            return packetBuffer;
        }
        public static ArraySegment<byte> Pack_SC_CreateAccount(long linkedAccountId)
        {
            var protocol = SCPacketProtocol.SC_CreateAccount;

            int bodySize = 0;
            bodySize += linkedAccountId.SizeForWrite();

            int packetSize = SCPacketHeader.HEADER_SIZE + bodySize;

            var packetBuffer = new ArraySegment<byte>(new byte[packetSize]);
            using(var encoder = new BinaryEncoder(packetBuffer))
            {
                WriteHeader(encoder, protocol, bodySize);
                encoder.Write(in linkedAccountId);
            }
            return packetBuffer;
        }
        public static ArraySegment<byte> Pack_SC_ChatMessage()
        {
            var protocol = SCPacketProtocol.SC_ChatMessage;

            int bodySize = 0;

            int packetSize = SCPacketHeader.HEADER_SIZE + bodySize;

            var packetBuffer = new ArraySegment<byte>(new byte[packetSize]);
            using(var encoder = new BinaryEncoder(packetBuffer))
            {
                WriteHeader(encoder, protocol, bodySize);
            }
            return packetBuffer;
        }
    }
}
