//======================================
//======       AutoGenerated       =====
//======================================

namespace Shared.Protocol
{
    public enum SCPacketProtocol: int
    {
        Invalid,

        SC_Pong,
        SC_Login,
        SC_CreateAccount,
        SC_ChatMessage,
    }
}
